#!/bin/bash
# docker-entrypoint.sh
# Runs before Apache starts on Render.
# 1. Decodes the base64 Aiven CA cert from env var into a .pem file
# 2. Writes all env vars into /var/www/html/env.production so Database.php can load them
# 3. Starts Apache

set -e

echo "[entrypoint] Starting JDB Parts container..."

# ── 1. Decode Aiven CA certificate ───────────────────────────────────────────
# AIVEN_CA_CERT must be set in Render as a base64-encoded string of the CA cert.
# To encode: base64 -w 0 ca.pem (Linux) or certutil -encode ca.pem ca_b64.txt (Windows)
if [ -n "$AIVEN_CA_CERT" ]; then
    echo "$AIVEN_CA_CERT" | base64 -d > /var/www/html/ca.pem
    echo "[entrypoint] Aiven CA cert written to /var/www/html/ca.pem"
else
    echo "[entrypoint] WARNING: AIVEN_CA_CERT not set. SSL to Aiven may fail."
fi

# ── 2. Write env.production from Render environment variables ─────────────────
# Database.php looks for env.production when APP_ENV != 'local'.
# Render injects env vars into the process but not into a file,
# so we write them here so Database.php::loadEnv() can find them.
cat > /var/www/html/env.production <<EOF
# Auto-generated by docker-entrypoint.sh at container start
# Do not edit manually — set values in Render dashboard

# Database (Aiven MySQL)
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT:-16431}
DB_NAME=${DB_NAME:-defaultdb}
DB_USER=${DB_USER:-avnadmin}
DB_PASS=${DB_PASS}

# App
APP_ENV=production
APP_DEBUG=false

# Aiven SSL — path to decoded CA cert
DB_SSL_CA=/var/www/html/ca.pem

# PayMongo
PAYMONGO_SECRET_KEY=${PAYMONGO_SECRET_KEY}
PAYMONGO_PUBLIC_KEY=${PAYMONGO_PUBLIC_KEY}
PAYMONGO_WEBHOOK_SECRET=${PAYMONGO_WEBHOOK_SECRET}

# SMTP
SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
SMTP_PORT=${SMTP_PORT:-587}
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
SMTP_FROM=${SMTP_FROM:-noreply@jdbparts.com}

# OAuth
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}

FB_CLIENT_ID=${FB_CLIENT_ID}
FB_CLIENT_SECRET=${FB_CLIENT_SECRET}
FB_REDIRECT_URI=${FB_REDIRECT_URI}

GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
GITHUB_REDIRECT_URI=${GITHUB_REDIRECT_URI}
EOF

echo "[entrypoint] env.production written."

# ── 3. Fix permissions ────────────────────────────────────────────────────────
chown www-data:www-data /var/www/html/env.production
chmod 600 /var/www/html/env.production

if [ -f /var/www/html/ca.pem ]; then
    chown www-data:www-data /var/www/html/ca.pem
    chmod 600 /var/www/html/ca.pem
fi

echo "[entrypoint] Launching Apache..."

# ── 4. Hand off to Apache ─────────────────────────────────────────────────────
exec "$@"